# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-03 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
