# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-21 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('0', '开发'), ('1', '测试'), ('2', '运维')], max_length=10, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='用户名称'),
        ),
    ]
