# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-10 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名必须唯一', max_length=16, unique=True, verbose_name='注册用户名')),
                ('password', models.CharField(max_length=32, verbose_name='登陆密码')),
            ],
        ),
    ]
