# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-17 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190616_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permisson',
            new_name='Permission',
        ),
    ]
