# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-19 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190618_1821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([]),
        ),
    ]
